sudo: false
language: php
php:
  - 5.6
before_script:
  - gem install dpl
script:
  - zip -r $TRAVIS_BUILD_NUMBER.package.zip . > /dev/null
before_deploy:
- mkdir -p dpl_cd_upload
- FILENAME=$TRAVIS_BUILD_NUMBER.package.zip
- cp $FILENAME dpl_cd_upload/
deploy:
- provider: elasticbeanstalk
  access-key-id: AKIAJ35YIGD6WQVEUV6A
  secret-access-key:
    secure: "j0lyJaI2p2NloWxUFn7JvhxhbfHJin+7UHTtFLzbQmVbb1gzkZtKYXk2IEK7b/Sxgxfmet5ENIqV6omlwsTRMf3ReLzaspZRAPymoDyzBju5akn7EcvNZqtLNzSOMSCQlzNlAs4J3GjhCMco/d7dYIt08kGTN4S1icK5iUEa/PXsQgkoMdqq6pbIlLiv2Z7HjflBK0CRiTuQMtZdcRmpsfk1WpZeiyS3KRWyzg3JFVwRJj9rJn4Yi0A0fRi57+fcgG7xcvuW71+Y/w1dc1OYcNk/kVWTETCg4X5e80Gs3eNCkr2ZDjZzx2Vag/Q7iif0EDrW/PIjOJ+wEl3CBR8ih9eAJNaaaOJ6VrZW+dV44V+x6ydSA2KnV+yQvwOksl3rDOFQ+qaIPgkDnvt3CgALWyKlldwVwUdEr4vTWJBmw7K980fL45mLLcmrVQsLFK0epuVewCKxiWlWEgZtnh1okkKp9U8y/NYj3TXbQ2LTfRNlAGyou2iK9kbv0T8B2WNuUkRuJXfvO0aZWIrTiJIUoKe1n1klvp6/Qrw2QILFUigHag8ZrwzALIPXZvSjpqA2aw1cVqfUAVi6rdpH2R1rPfaBFP+Z1XZm/bmsD54l/kIc0YYqdYVRJhyHvxXr43vAThEfhko6vXQLSU4omjSbi/v4a1YqNcZTEoHHfJdwBrA="
  bucket_name: wordpress-blog-deployments
  bucket_path: 'releases'
  zip-file: 'dpl_cd_upload/$TRAVIS_BUILD_NUMBER.package.zip'
  app: Blog
  env: production
  skip_cleanup: true
  on:
    repo: rlgod/danielparker.com.au-wordpress
    branch: release
  region: ap-southeast-2
branches:
  only:
  - release
