sudo: false
language: php
php:
  - 5.6
before_script:
  - gem install dpl
script:
  - zip -r $TRAVIS_BUILD_NUMBER.package.zip . > /dev/null
before_deploy:
- mkdir -p dpl_cd_upload
- FILENAME=$TRAVIS_BUILD_NUMBER.package.zip
- cp $FILENAME dpl_cd_upload/
deploy:
- provider: elasticbeanstalk
  access-key-id: AKIAJ35YIGD6WQVEUV6A
  secret-access-key:
    secure: "0Per4y/LZmLwQhLwyuKizQuboedcaDsFVyw04PDEIFuV22tFz+NW6BHPaR0DNubDtDBew93ETxsDlZjNAWE2/dvoporafsxlueA9qVXdxfSs05za9AgEDoPY0d+Fzg7PV/pex81OD1qgTsfNoQpcM9JbX9z8lS5Yp0aCGYiT9x6s7bh+k8u1qLAcZS720yCVrCgRvu8JFf38RcUVVm83VbCDfwjcT1316ZE0k0FQSMmttWejZqTsMmUzDhbJU1d9PaZ5xmGfHbeDJ+dLp/8Daaigrdf7GXpMIr1UF/KTXiUKupLE0u2fVVW6V9XqHz0RK9mjyJ8MVC05GQr/Oje/F6SKrAmDvAL1ehab9OEnO1/MdYzUWl4xDLmR8wPBy4a5kub775mL1DAWLn9WaweymkhOWuV5eNXXRnWM1a674RJ8o6z4LpuY1RToEKgHlf52/VLApbyL8LPVFYqwrvIyaxm2mzmqJlRC6CGdy1vjfl9Sze7ddw9GOYoq0PlZFD9Qj3A43h0zR2IlIx65xe+DJFJUqhD1LxKup7WZbaPgvDPGhxF/zrDAXmfCVve21gKlvH/Xf5m78/sa1OvI2I3JNg031iA4MJMb70ZBWMbwTDfYGvXiZ49lM2JzUhtS1pNhUN6A4C3DuhimEc1E6WJw2gmGno/CDauDxOQxDAvqHao="
  bucket_name: wordpress-blog-deployments
  bucket_path: 'releases'
  zip-file: 'dpl_cd_upload/$TRAVIS_BUILD_NUMBER.package.zip'
  app: Blog
  env: production
  skip_cleanup: true
  on:
    repo: rlgod/danielparker.com.au-wordpress
    branch: release
  region: ap-southeast-2
branches:
  only:
  - release
notifications:
  slack:
    secure: vDYKi5LiLTV8ohu9sJKdeSUqaGSgn3R6xRuFo2xQCYwkEUHlFC618zLjmgFEYaI628UWYLzBPMt4NkRm2veKyMeIkgIVvNmJdX6pxVLCvC4x/h1GIiwQUciKdPmOjeeq1biFbdKMHVbsIM3qNLqcrue
