sudo: false
language: php
php:
  - 5.6
before_script:
  - gem install dpl
script:
  - zip -r $TRAVIS_BUILD_NUMBER.package.zip . > /dev/null
before_deploy:
- mkdir -p dpl_cd_upload
- FILENAME=$TRAVIS_BUILD_NUMBER.package.zip
- cp $FILENAME dpl_cd_upload/
deploy:
- provider: elasticbeanstalk
  access-key-id: AKIAJ35YIGD6WQVEUV6A
  secret-access-key:
    secure: lfOceF7BHYukrpU1QmT/UfHgdpTTloez313AzAHw4wJDGtyQpZK/a94IYgi5wu5c9+XlPXBKap2XTEtc0uky6nDsL3jwm4K2MdnF1LsdfgyDHU7sGRBt/ep9zkuvsYMra84Jp9GkSp8WVJijr0M4ZKmPoV9/U+ydh285QXDEMwIWY+nyD1Gl3hTAQTKT+mO3t64rREf+iKsgu8Fvcxpu2TjonsRfjTa3A3c5HueYcWnclG41cnVmSy//6q1DP1ApYypqBaRsFcfweB2lXJ3Kk0lRc0aLV+NGJYMeGFJlXopKp/zhVmvS0p5A3dIMNE6ClPNGlU3GnGEhJjU9v9UkkQauHVTY9QAxOhNDNVtMoe2BnbU4DdK9wqzbHeTTD/TmGPhKBHAIVe7GMJ3chf/ai1X9uCD6ifLxtAVpKr2IT4IFM9U3cx5U5SHyVhbqZ6B6ZkW863ER1qaiWtFWD07NhDxeXm21F1paWYEAtOeF8BlYjnhfhrlaQhed7CpJAmaYsH/CnITYHJ6Uk7TOBWlMl418thTRq+LTFqwATXESlnF5vZJBLneQh+a+nmMUzP+uGOALRSVaX6MWN8p89ZtgFJf2KYqGZkKbwfWM+vtkx5IJgizGiQ5DSyyjSoVwDV10O0CyBl2PZO1pd5wSK/XTTonRajlP+W+Dsu6mTX0Nvns=
  bucket_name: wordpress-blog-deployments
  bucket_path: 'releases'
  zip-file: 'dpl_cd_upload/$TRAVIS_BUILD_NUMBER.package.zip'
  app: Wordpress-blog
  env: production
  skip_cleanup: true
  on:
    repo: rlgod/danielparker.com.au-wordpress
    branch: release
  region: ap-southeast-2
branches:
  only:
  - release
